### ISSUE TITLE
What is the "back-end" in GrammarChecker.md?

### ISSUE THREAD

**Issue by unhammer** [divvun/DivvunPublicTenders#2]
The document first says `the front-end should check with the back-end server for new versions`, which makes it sound like the back-end is a centralised server.

But then `send and receive a paragraph of text to the back-end` along with the offline requirement makes it seem like it's just part of the plugin bundle running on the user's machine.

**Comment by snomos** [comment]
@unhammer - check whether my changes address the points you raised in this bug.
